%YAML 1.2
---
protocol:
  title: arithmetic-testing
  version: '1.1'
  description: Test workflow using the arithmetic calcjobs/work chains from
    aiida-core.
  dependencies:
  - [aiida-core, '2.0', null]
  parent_node_type: float
  parent_node_input: {task_1.1: x, task_1.2: x, task_1.3: z, task_2.2: x}
  tasks:
    task_1.1: {process: core.arithmetic.add_multiply}
    task_1.2: {process: core.arithmetic.add_multiply}
    task_1.3: {process: core.arithmetic.add_multiply}
    task_2.1:
      process: core.arithmetic.add_multiply
      dependencies:
        task_1.2:
        - [result, x]
        task_1.3:
        - [result, z]
    task_2.2:
      process: core.arithmetic.add_multiply
      dependencies:
        task_1.3:
        - [result, y]
    task_3.1:
      process: core.arithmetic.add_multiply
      dependencies:
        task_1.1:
        - [result, x]
        task_2.1:
        - [result, y]
        task_2.2:
        - [result, z]
    task_4.1:
      process: core.arithmetic.add_multiply
      dependencies:
        task_3.1:
        - [result, x]
        task_1.2:
        - [result, z]
  general_input:
    z:
      value: 2.0
      aiida_node: true
      tasks: [task_1.1, task_2.2]
    z->task_1.2: {value: 4.0, aiida_node: true}
    x->task_1.3: {value: 10.0, aiida_node: true}
  user_input:
    y:
      validation:
      aiida_node: true
      compare: true
      tasks: [task_1.1, task_1.2, task_1.3, task_2.1]
    y->task_4.1: {validation: null, aiida_node: true, compare: true}
  results:
    res_1: {task: task_4.1, output_port: result, unit: test_unit}
    res_2: {task: task_1.3, output_port: result, unit: test_unit}
general_input: {z: 5222b4fc-04e3-4e46-a3b3-8397e934deb4, z->task_1.2:
    3158a97c-0f4e-4616-99e4-17ac5b759f2a}
user_input_nodes: {y: 78329aac-d834-4edf-bcf5-43bed1b97127, y->task_4.1:
    d7a643fc-6026-4ade-841f-9670ba5afce0}
user_input: {}
parent_node: 1b9466de-0dba-4628-a991-32dc81f67e03
